### PR TITLE
Adding a few more endpoints

### PR DESCRIPTION
**Pull request by ghost**
This includes nearly everything in the top of /meta-data.

Has been given a quick test under `go1.8 darwin/amd64`.

### CODE REVIEW

**Comment by ghost** [comment]
Oh dear...

**Comment by jimbydamonk** [comment]
Ouch. Looks like there are some issues with dependencies on gizmo. I will take a peak

**Comment by jimbydamonk** [comment]
Can you try re basing?  I check the gizmo stuff and it _should_ work.

**Comment by ghost** [comment]
Okay, it looks like that now passes. Could you please review?

**Comment by jimbydamonk** [comment]
Thanks, and sorry for the trouble!

**Pull request merged**
